### ISSUE TITLE
兄弟,推荐一家GY-91 MPU9250吧  我都买了三个假货了 ;-( 

### ISSUE THREAD

**Issue by robinluyi** [sin1111yi/stm32_mpu9250_spi_hal_lib#1]
我买了三块MPU9250, 都是假的, 读不到磁力计. 
看了你的文章才注意到, WHOAMI 都是70.
可不可以推荐一个卖真货的卖家? 

https://blog.csdn.net/sin1111yi/article/details/121906053

**Comment by sin1111yi** [comment]
https://detail.tmall.com/item.htm?spm=a1z10.3-b-s.w4011-21827954511.34.6c3a4cb2DKMNbJ&id=601197606695&rn=f2b4c0cdac4a3499314ada13bcc445f0&abbucket=20
另外我现在不建议你继续使用MPU9250这个芯片了，首先是因为已经停产了，其次是用起来比用一个6轴和一个磁力计更麻烦，最后是成本问题，两个芯片可能成本还更低
